### ISSUE TITLE
[help] Could you provide the preprocessed ml-1m datasets?

### ISSUE THREAD

**Issue by yeeeqichen** [salesforce/ICLRec#3]
Hi @YChen1993 , 

Thanks for your great effort.

As the title suggests, could you provide an extra preprocessed ml-1m datasets, or the corresponding pre-processing scripts? I meet some troubles when apply your method on ml-1m, since I don't know the way that you preprocess the dataset.

Thanks!

**Comment by YChen1993** [comment]
Hi @yeeeqichen, thanks for asking!

I just uploaded the prepared ml-1m dataset. Specifically, I use the data prepared by SASRec [here](https://github.com/kang205/SASRec/blob/master/data/ml-1m.txt). I basically just convert the original flattened data format (one interaction per row) into the nested format (one user's interactions per row). You can run the script by ```python3 main.py --data_name ml-1m```. 

Although I did not report the ml-1m results in paper, I used to run our method with some default hyper-parameters (as well as a few latest developed baselines) on ml-1m. A quick snapshot is that no significant improvements are made upon SASRec on ml-1m. You can have a try and tune the hyperparameters in a granular manner. 

Please feel free to let me know if you have any questions or observations. Thanks!

**Comment by yeeeqichen** [comment]
Thank your so much!
