### ISSUE TITLE
Could you please provide the best hyper-parameters?

### ISSUE THREAD

**Issue by ShadowTinker** [salesforce/ICLRec#7]
Hi, @YChen1993 , Thanks for your great work and repo!

I don't find the best hyper-parameters in the paper, and I find the contrastive learning weights provided in `src/scripts/*.sh` are basically the same, which I guess are not the best hyper-parameters. So could I trouble you to provide the best hyper-parameters of ICLRec on the four datasets? I would really appreciate it if you could help me with the hyper-parameters.

Thank you!

**Comment by yueliu1999** [comment]
Could you please provide the best hyper-parameters?

**Comment by ShadowTinker** [comment]
Hi @yueliu1999 , I recently found that the hyper-parameters provided in the scripts are basically optimal.
